=== Rohi-184/WT_Lab/Exercise 13/Students.dtd
<!ELEMENT students (student+)>

<!ELEMENT student (name, age, course, grade)>

<!ELEMENT name (#PCDATA)>

<!ELEMENT age (#PCDATA)>

<!ELEMENT course (#PCDATA)>

<!ELEMENT grade (#PCDATA)>

<!ATTLIST student
    id ID #REQUIRED
>

=== Rohi-184/WT_Lab/Exercise 13/Student.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE students SYSTEM "Students.dtd">

<students>

    <student id="s101">

        <name>Vishnu</name>

        <age>23</age>

        <course>MCA</course>

        <grade>A</grade>

    </student>


    <student id="s102">

        <name>Rahul</name>

        <age>21</age>

        <course>MCA</course>

        <grade>B</grade>

    </student>


    <student id="s103">

        <name>Ravi</name>

        <age>22</age>

        <course>MCA</course>

        <grade>C</grade>

    </student>


    <student id="s104">

        <name>Vicky</name>

        <age>23</age>

        <course>MCA</course>

        <grade>A</grade>

    </student>

</students>
